// <auto-generated />
using System;
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PrimeiraApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Api.Models.FolhaPagamento", b =>
                {
                    b.Property<int>("FolhaPagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ImpostoDeRenda")
                        .HasColumnType("REAL");

                    b.Property<double>("ImpostoFgts")
                        .HasColumnType("REAL");

                    b.Property<double>("ImpostoInss")
                        .HasColumnType("REAL");

                    b.Property<int>("MesPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeHorar")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SalarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<int>("UserModelID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorHora")
                        .HasColumnType("REAL");

                    b.HasKey("FolhaPagamentoId");

                    b.HasIndex("UserModelID")
                        .IsUnique();

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("Api.Models.UserModel", b =>
                {
                    b.Property<int>("UserModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cpf")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("TEXT");

                    b.HasKey("UserModelId");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("Api.Models.FolhaPagamento", b =>
                {
                    b.HasOne("Api.Models.UserModel", "Usuario")
                        .WithOne("Folha")
                        .HasForeignKey("Api.Models.FolhaPagamento", "UserModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Api.Models.UserModel", b =>
                {
                    b.Navigation("Folha")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
